export const MILEAGEDISENGAGE_LIST_REQUEST = "MILEAGEDISENGAGE_LIST_REQUEST";
export const MILEAGEDISENGAGE_LIST_SUCCESS = "MILEAGEDISENGAGE_LIST_SUCCESS";
export const MILEAGEDISENGAGE_LIST_FAIL = "MILEAGEDISENGAGE_LIST_FAIL";