export const SUGGESTION_CREATE_REQUEST = "SUGGESTION_CREATE_REQUEST";
export const SUGGESTION_CREATE_SUCCESS = "SUGGESTION_CREATE_SUCCESS";
export const SUGGESTION_CREATE_FAIL = "SUGGESTION_CREATE_FAIL";

export const SUGGESTION_UPDATE_REQUEST = "SUGGESTION_UPDATE_REQUEST";
export const SUGGESTION_UPDATE_SUCCESS = "SUGGESTION_UPDATE_SUCCESS";
export const SUGGESTION_UPDATE_FAIL = "SUGGESTION_UPDATE_FAIL";

